// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	translate "github.com/rizadwiandhika/miniproject-backend-alterra/third-parties/translate"
	mock "github.com/stretchr/testify/mock"
)

// IBusiness is an autogenerated mock type for the IBusiness type
type IBusiness struct {
	mock.Mock
}

// Translate provides a mock function with given fields: t
func (_m *IBusiness) Translate(t translate.TranslateCore) (string, error) {
	ret := _m.Called(t)

	var r0 string
	if rf, ok := ret.Get(0).(func(translate.TranslateCore) string); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(translate.TranslateCore) error); ok {
		r1 = rf(t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
